# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(384, 323)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.label.setStyleSheet("font: 15pt \"Impact\";\n"
"background-color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 41, 16))
        self.label_2.setStyleSheet("font: 10pt \"Impact\";\n"
"color: rgb(75, 75, 75);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 31, 16))
        self.label_3.setStyleSheet("font: 10pt \"Impact\";\n"
"color: rgb(75, 75, 75);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 130, 51, 16))
        self.label_4.setStyleSheet("font: 10pt \"Impact\";\n"
"color: rgb(75, 75, 75);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 160, 31, 16))
        self.label_5.setStyleSheet("font: 10pt \"Impact\";\n"
"color: rgb(75, 75, 75);")
        self.label_5.setObjectName("label_5")
        self.confirmar = QtWidgets.QPushButton(self.centralwidget)
        self.confirmar.setGeometry(QtCore.QRect(160, 240, 75, 23))
        self.confirmar.setStyleSheet("font: 10pt \"Impact\";\n"
"background-color: rgb(255, 0, 0);")
        self.confirmar.setObjectName("confirmar")
        self.termosUso = QtWidgets.QRadioButton(self.centralwidget)
        self.termosUso.setGeometry(QtCore.QRect(70, 200, 261, 17))
        self.termosUso.setStyleSheet("")
        self.termosUso.setObjectName("termosUso")
        self.inputNome = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNome.setGeometry(QtCore.QRect(100, 70, 221, 20))
        self.inputNome.setPlaceholderText("")
        self.inputNome.setObjectName("inputNome")
        self.inputCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCPF.setGeometry(QtCore.QRect(100, 100, 221, 20))
        self.inputCPF.setObjectName("inputCPF")
        self.inputTelefone = QtWidgets.QLineEdit(self.centralwidget)
        self.inputTelefone.setGeometry(QtCore.QRect(100, 130, 221, 20))
        self.inputTelefone.setObjectName("inputTelefone")
        self.inputEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.inputEmail.setGeometry(QtCore.QRect(100, 160, 221, 20))
        self.inputEmail.setObjectName("inputEmail")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 384, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Cadastro de Usuário</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Nome"))
        self.label_3.setText(_translate("MainWindow", "CPF"))
        self.label_4.setText(_translate("MainWindow", "Telefone"))
        self.label_5.setText(_translate("MainWindow", "Email"))
        self.confirmar.setText(_translate("MainWindow", "Confirmar"))
        self.termosUso.setText(_translate("MainWindow", "Li e concordo com os Termos e Condições de Uso."))
        self.inputNome.setText(_translate("MainWindow", "Insira seu nome"))
        self.inputCPF.setText(_translate("MainWindow", "Insira CPF"))
        self.inputTelefone.setText(_translate("MainWindow", "Insira seu telefone"))
        self.inputEmail.setText(_translate("MainWindow", "Insira seu email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
